name: ci
on: [push]
jobs:
  run-ci-steps-rc17:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 16.13
    - name: Install all dependencies
      run: npm ci
    - name: Run the tests with vue-test-utils 2.0.0-rc.17
      run: npm run test

  run-ci-steps-rc18:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 16.13
    - name: Install all dependencies
      run: npm ci
    - name: Install vue-test-utils 2.0.0-rc.18
      run: npm install --save-dev @vue/test-utils@2.0.0-rc.18
    - name: Run the tests with vue-test-utils 2.0.0-rc.18
      run: npm run test
